import {
  RUN_STATES,
  TERMINAL_STATES,
  type RunState,
} from "./contracts.js";

const terminalSet = new Set<RunState>(TERMINAL_STATES);

export const STATE_TRANSITIONS: Readonly<Record<RunState, readonly RunState[]>> = {
  REQUEST_RECEIVED: ["REQUEST_NORMALIZED", "CLARIFICATION_REQUIRED", "RETRY_BUDGET_EXHAUSTED", "REJECTED", "CANCELLATION_PENDING"],
  REQUEST_NORMALIZED: ["PLANNING", "CLARIFICATION_REQUIRED", "REJECTED", "CANCELLATION_PENDING"],
  CLARIFICATION_REQUIRED: ["REQUEST_NORMALIZED", "PLANNING", "REJECTED", "TIMED_OUT", "CANCELLATION_PENDING"],
  PLANNING: ["PLAN_READY", "CLARIFICATION_REQUIRED", "REPLANNING", "RETRY_BUDGET_EXHAUSTED", "FAILED", "CANCELLATION_PENDING"],
  PLAN_READY: ["PLAN_FROZEN", "REPLANNING", "CLARIFICATION_REQUIRED", "REJECTED", "CANCELLATION_PENDING"],
  PLAN_FROZEN: ["QUEUED", "SANDBOX_WARM_REQUESTED", "SANDBOX_WARM_CLAIMING", "SANDBOX_COLD_PROVISIONING", "CANCELLATION_PENDING"],
  QUEUED: ["SANDBOX_WARM_CLAIMING", "SANDBOX_COLD_PROVISIONING", "TIMED_OUT", "CANCELLATION_PENDING"],
  SANDBOX_WARM_REQUESTED: ["SANDBOX_WARM_AVAILABLE", "SANDBOX_COLD_PROVISIONING", "BLOCKED_BY_ENVIRONMENT", "CANCELLATION_PENDING"],
  SANDBOX_WARM_AVAILABLE: ["SANDBOX_WARM_CLAIMING", "SANDBOX_COLD_PROVISIONING", "TIMED_OUT", "CANCELLATION_PENDING"],
  SANDBOX_WARM_CLAIMING: ["SANDBOX_WARM_VALIDATING", "SANDBOX_PREWARM_INVALID", "SANDBOX_COLD_PROVISIONING", "QUEUED", "RETRY_BUDGET_EXHAUSTED", "CANCELLATION_PENDING"],
  SANDBOX_WARM_VALIDATING: ["SANDBOX_WARM_CLAIMED", "SANDBOX_PREWARM_INVALID", "QUEUED", "RETRY_BUDGET_EXHAUSTED", "CANCELLATION_PENDING"],
  SANDBOX_WARM_CLAIMED: ["SANDBOX_READY", "SANDBOX_PREWARM_INVALID", "QUEUED", "RETRY_BUDGET_EXHAUSTED", "CANCELLATION_PENDING"],
  SANDBOX_COLD_PROVISIONING: ["SANDBOX_PREFLIGHT", "SANDBOX_PROVISIONING", "BLOCKED_BY_ENVIRONMENT", "QUEUED", "RETRY_BUDGET_EXHAUSTED", "CANCELLATION_PENDING"],
  SANDBOX_PREWARM_INVALID: ["SANDBOX_COLD_PROVISIONING", "BLOCKED_BY_ENVIRONMENT", "QUEUED", "RETRY_BUDGET_EXHAUSTED", "CANCELLATION_PENDING"],
  SANDBOX_PROVISIONING: ["SANDBOX_PREFLIGHT", "BLOCKED_BY_ENVIRONMENT", "QUEUED", "RETRY_BUDGET_EXHAUSTED", "CANCELLATION_PENDING"],
  SANDBOX_PREFLIGHT: ["SANDBOX_READY", "BLOCKED_BY_ENVIRONMENT", "SECURITY_ESCALATION", "QUEUED", "RETRY_BUDGET_EXHAUSTED", "CANCELLATION_PENDING"],
  SANDBOX_READY: ["IMPLEMENTING", "CONTEXT_BUILDING", "QUEUED", "RETRY_BUDGET_EXHAUSTED", "CANCELLATION_PENDING"],
  CONTEXT_BUILDING: ["IMPLEMENTING", "BLOCKED_BY_ENVIRONMENT", "BLOCKED_BY_EXTERNAL_DEPENDENCY", "QUEUED", "RETRY_BUDGET_EXHAUSTED", "CANCELLATION_PENDING"],
  IMPLEMENTING: ["FAST_CHECKS", "REPLANNING", "QUEUED", "RETRY_BUDGET_EXHAUSTED", "FAILED", "CANCELLATION_PENDING"],
  FAST_CHECKS: ["UNIT_TESTING", "IMPLEMENTING", "RETRY_BUDGET_EXHAUSTED", "VERIFICATION_INCOMPLETE", "CANCELLATION_PENDING"],
  UNIT_TESTING: ["INTEGRATION_TESTING", "IMPLEMENTING", "FLAKE_QUARANTINE", "RETRY_BUDGET_EXHAUSTED", "VERIFICATION_INCOMPLETE", "CANCELLATION_PENDING"],
  INTEGRATION_TESTING: ["E2E_TESTING", "SECURITY_REVIEW", "IMPLEMENTING", "FLAKE_QUARANTINE", "RETRY_BUDGET_EXHAUSTED", "VERIFICATION_INCOMPLETE", "CANCELLATION_PENDING"],
  E2E_TESTING: ["SECURITY_REVIEW", "IMPLEMENTING", "FLAKE_QUARANTINE", "RETRY_BUDGET_EXHAUSTED", "VERIFICATION_INCOMPLETE", "CANCELLATION_PENDING"],
  FLAKE_QUARANTINE: ["UNIT_TESTING", "INTEGRATION_TESTING", "VERIFICATION_INCOMPLETE", "HUMAN_REVIEW_REQUIRED", "CANCELLATION_PENDING"],
  SECURITY_REVIEW: ["EVIDENCE_SYNTHESIS", "CODE_REVIEW", "REVIEWING", "IMPLEMENTING", "RETRY_BUDGET_EXHAUSTED", "SECURITY_ESCALATION", "CANCELLATION_PENDING"],
  CODE_REVIEW: ["REVIEWING", "REVIEW_APPROVED", "REVIEW_CHANGES_REQUESTED", "REVIEW_REJECTED", "CANCELLATION_PENDING"],
  EVIDENCE_SYNTHESIS: ["REVIEWING", "VERIFICATION_INCOMPLETE", "FAILED", "CANCELLATION_PENDING"],
  REVIEWING: ["REVIEW_APPROVED", "REVIEW_CHANGES_REQUESTED", "REVIEW_REJECTED", "RETRY_BUDGET_EXHAUSTED", "HUMAN_REVIEW_REQUIRED", "CANCELLATION_PENDING"],
  REVIEW_APPROVED: ["HUMAN_APPROVAL_PENDING", "PR_PREFLIGHT", "CANCELLATION_PENDING"],
  REVIEW_CHANGES_REQUESTED: ["REVIEW_FIX_PREPARING", "REPLANNING", "RETRY_BUDGET_EXHAUSTED", "HUMAN_REVIEW_REQUIRED", "CANCELLATION_PENDING"],
  REVIEW_FIX_PREPARING: ["IMPLEMENTING", "REPLANNING", "RETRY_BUDGET_EXHAUSTED", "CANCELLATION_PENDING"],
  REVERIFYING: ["FAST_CHECKS", "VERIFICATION_INCOMPLETE", "CANCELLATION_PENDING"],
  REVIEW_REJECTED: ["REJECTED", "HUMAN_REVIEW_REQUIRED", "CANCELLATION_PENDING"],
  HUMAN_APPROVAL_PENDING: ["HUMAN_APPROVED", "FIX_REQUESTED", "REJECTED", "HUMAN_REVIEW_REQUIRED", "TIMED_OUT", "CANCELLATION_PENDING"],
  HUMAN_APPROVED: ["PR_PREFLIGHT", "BASE_BRANCH_STALE", "CANCELLATION_PENDING"],
  FIX_REQUESTED: ["REVIEW_FIX_PREPARING", "REPLANNING", "REJECTED", "CANCELLATION_PENDING"],
  REPLANNING: ["PLAN_READY", "CLARIFICATION_REQUIRED", "RETRY_BUDGET_EXHAUSTED", "REJECTED", "FAILED", "CANCELLATION_PENDING"],
  PR_PREFLIGHT: ["PR_CREATING", "BASE_BRANCH_STALE", "PR_CREATION_FAILED", "SECURITY_ESCALATION", "CANCELLATION_PENDING"],
  PR_CREATING: ["PR_CREATED", "PR_CREATION_FAILED", "BASE_BRANCH_STALE", "CANCELLATION_PENDING"],
  PR_CREATED: ["COMPLETED", "FAILED", "CANCELLATION_PENDING"],
  PR_CREATION_FAILED: ["PR_PREFLIGHT", "HUMAN_REVIEW_REQUIRED", "FAILED", "CANCELLATION_PENDING"],
  BASE_BRANCH_STALE: ["REVERIFYING", "REPLANNING", "HUMAN_REVIEW_REQUIRED", "CANCELLATION_PENDING"],
  ROLLBACK_IN_PROGRESS: ["ROLLED_BACK", "FAILED"],
  CANCELLATION_PENDING: ["CANCELLED", "ROLLBACK_IN_PROGRESS", "FAILED"],
  EVIDENCE_PACKAGING: ["COMPLETED", "VERIFICATION_INCOMPLETE", "FAILED", "CANCELLATION_PENDING"],
  COMPLETED: [],
  REJECTED: [],
  CANCELLED: [],
  TIMED_OUT: [],
  RETRY_BUDGET_EXHAUSTED: [],
  BLOCKED_BY_ENVIRONMENT: [],
  BLOCKED_BY_EXTERNAL_DEPENDENCY: [],
  SECURITY_ESCALATION: [],
  HUMAN_REVIEW_REQUIRED: [],
  VERIFICATION_INCOMPLETE: [],
  ROLLED_BACK: [],
  FAILED: [],
};

export interface StateRuntimePolicy {
  maxDurationSeconds: number;
  heartbeatExpected: boolean;
  retryClass: "NONE" | "MODEL" | "SANDBOX" | "BUILDER" | "REVIEWER" | "HUMAN" | "GIT";
  cancellationState: "CANCELLATION_PENDING" | null;
}

function runtimePolicy(state: RunState): StateRuntimePolicy {
  if (terminalSet.has(state)) {
    return { maxDurationSeconds: 0, heartbeatExpected: false, retryClass: "NONE", cancellationState: null };
  }
  if (state.startsWith("SANDBOX_")) {
    return { maxDurationSeconds: 300, heartbeatExpected: true, retryClass: "SANDBOX", cancellationState: "CANCELLATION_PENDING" };
  }
  if (state === "IMPLEMENTING" || state === "REVERIFYING") {
    return { maxDurationSeconds: 1_800, heartbeatExpected: true, retryClass: "BUILDER", cancellationState: "CANCELLATION_PENDING" };
  }
  if (state === "REVIEWING" || state.startsWith("REVIEW_")) {
    return { maxDurationSeconds: 900, heartbeatExpected: true, retryClass: "REVIEWER", cancellationState: "CANCELLATION_PENDING" };
  }
  if (state.startsWith("HUMAN_")) {
    return { maxDurationSeconds: 86_400, heartbeatExpected: false, retryClass: "HUMAN", cancellationState: "CANCELLATION_PENDING" };
  }
  if (state.startsWith("PR_") || state === "BASE_BRANCH_STALE") {
    return { maxDurationSeconds: 600, heartbeatExpected: true, retryClass: "GIT", cancellationState: "CANCELLATION_PENDING" };
  }
  if (state === "PLANNING" || state === "REPLANNING") {
    return { maxDurationSeconds: 900, heartbeatExpected: true, retryClass: "MODEL", cancellationState: "CANCELLATION_PENDING" };
  }
  return { maxDurationSeconds: 900, heartbeatExpected: false, retryClass: "NONE", cancellationState: "CANCELLATION_PENDING" };
}

export const STATE_RUNTIME_POLICIES: Readonly<Record<RunState, StateRuntimePolicy>> =
  Object.fromEntries(RUN_STATES.map((state) => [state, runtimePolicy(state)])) as Record<RunState, StateRuntimePolicy>;

export function isTerminalState(state: RunState): boolean {
  return terminalSet.has(state);
}

export function canTransition(previousState: RunState, nextState: RunState): boolean {
  return STATE_TRANSITIONS[previousState]?.includes(nextState) ?? false;
}
